<?php

namespace Mollsoft\LaravelTronModule\Services;

use Illuminate\Support\Facades\App;
use Mollsoft\LaravelTronModule\Models\TronNode;

class TronSync extends BaseSync
{
    public function run(): void
    {
        parent::run(); // TODO: Change the autogenerated stub

        $this->syncNodes();
    }

    protected function syncNodes(): self
    {
        /** @var class-string<TronNode> $model */
        $model = config('tron.models.node');

        $model::query()
            ->each(function (TronNode $node) {
                $this->log('--- Staring sync Node '.$node->name.'...');

                $service = App::make(NodeSync::class, [
                    'node' => $node
                ]);

                $service->setLogger($this->logger);

                $service->run();

                $this->log('--- Finished sync Node '.$node->name, 'success');
            });

        return $this;
    }
}